services:
  - type: web
    name: wedding-face-recognition-system
    runtime: docker
    plan: free
    envVars:
      - key: PYTHONPATH
        value: backend
      - key: DEV
        value: "false"




