services:
  - type: web
    name: wedding-face-recognition-system
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/run.py
    envVars:
      - key: PYTHONPATH
        value: backend
      - key: DEV
        value: "false"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
